/**
 * Export utilities for Chimera Command Center
 * Handles code export in multiple formats (single file, ZIP, clipboard)
 */

import JSZip from "jszip";

export type Framework = "react" | "vue" | "svelte" | "vanilla";

export interface ExportFile {
  filename: string;
  content: string;
}

export interface TeamCodeData {
  team: "anthropic" | "google";
  code: string;
  framework: Framework;
}

/**
 * Get file extension based on framework
 */
export function getFileExtension(framework: Framework): string {
  const extensions: Record<Framework, string> = {
    react: "tsx",
    vue: "vue",
    svelte: "svelte",
    vanilla: "js",
  };
  return extensions[framework] || "js";
}

/**
 * Format code for export with proper indentation and cleanup
 */
export function formatCodeForExport(
  code: string,
  framework: Framework
): string {
  // Remove any leading/trailing whitespace
  let formatted = code.trim();

  // Ensure consistent line endings
  formatted = formatted.replace(/\r\n/g, "\n");

  // Add framework-specific formatting
  switch (framework) {
    case "react":
      // Ensure React imports are present if not already
      if (!formatted.includes("import React") && !formatted.includes("'use client'")) {
        formatted = `import React from 'react';\n\n${formatted}`;
      }
      break;
    case "vue":
      // Ensure Vue template structure
      if (!formatted.includes("<template>")) {
        formatted = `<template>\n  ${formatted}\n</template>\n\n<script setup>\n// Add your script here\n</script>`;
      }
      break;
    case "svelte":
      // Svelte components are already structured
      break;
    case "vanilla":
      // Vanilla JS is already structured
      break;
  }

  return formatted;
}

/**
 * Download content as a file using browser API
 */
export function downloadAsFile(
  content: string,
  filename: string,
  mimeType: string = "text/plain"
): void {
  try {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error("Error downloading file:", error);
    throw new Error("Failed to download file");
  }
}

/**
 * Copy text to clipboard
 */
export async function copyToClipboard(text: string): Promise<void> {
  try {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      await navigator.clipboard.writeText(text);
    } else {
      // Fallback for older browsers
      const textarea = document.createElement("textarea");
      textarea.value = text;
      textarea.style.position = "fixed";
      textarea.style.opacity = "0";
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
    }
  } catch (error) {
    console.error("Error copying to clipboard:", error);
    throw new Error("Failed to copy to clipboard");
  }
}

/**
 * Generate README content for export package
 */
function generateReadme(
  teams: TeamCodeData[],
  task?: string
): string {
  const timestamp = new Date().toISOString();
  const teamsList = teams.map((t) => t.team).join(", ");

  return `# Chimera Export

**Generated:** ${new Date(timestamp).toLocaleString()}
**Teams:** ${teamsList}
**Framework:** ${teams[0]?.framework || "react"}

## Overview

This package contains code generated by Chimera AI teams in response to the following task:

${task ? `> ${task}` : "_No task description provided_"}

## Structure

${teams
  .map(
    (team) => `- \`${team.team}/\` - Code generated by ${team.team.charAt(0).toUpperCase() + team.team.slice(1)} team`
  )
  .join("\n")}

## Usage

Each team's output is in its respective directory. Review both implementations and choose the one that best fits your needs, or combine elements from both.

## Teams

${teams
  .map(
    (team) => `### ${team.team.charAt(0).toUpperCase() + team.team.slice(1)}
- Model: ${team.team === "anthropic" ? "Claude Sonnet 4.5" : "Gemini 2.0 Flash"}
- Output: \`${team.team}/Component.${getFileExtension(team.framework)}\`
`
  )
  .join("\n")}

---

*Generated by Chimera - AI-Powered Development Orchestrator*
`;
}

/**
 * Export single team's code as a file
 */
export function exportSingleFile(teamData: TeamCodeData): void {
  const { team, code, framework } = teamData;

  if (!code || code.trim() === "") {
    throw new Error(`No code available for ${team}`);
  }

  const formatted = formatCodeForExport(code, framework);
  const extension = getFileExtension(framework);
  const filename = `chimera-${team}-component.${extension}`;

  downloadAsFile(formatted, filename, "text/plain");
}

/**
 * Export multiple teams' code as a ZIP file
 */
export async function exportAsZip(
  teams: TeamCodeData[],
  task?: string
): Promise<void> {
  if (teams.length === 0) {
    throw new Error("No team data to export");
  }

  try {
    const zip = new JSZip();
    const rootFolder = zip.folder("chimera-export");

    if (!rootFolder) {
      throw new Error("Failed to create root folder");
    }

    // Add README
    const readme = generateReadme(teams, task);
    rootFolder.file("README.md", readme);

    // Add each team's code
    teams.forEach((teamData) => {
      const { team, code, framework } = teamData;

      if (!code || code.trim() === "") {
        console.warn(`Skipping ${team} - no code available`);
        return;
      }

      const teamFolder = rootFolder.folder(team);
      if (teamFolder) {
        const formatted = formatCodeForExport(code, framework);
        const extension = getFileExtension(framework);
        teamFolder.file(`Component.${extension}`, formatted);
      }
    });

    // Generate ZIP and download
    const blob = await zip.generateAsync({ type: "blob" });
    const timestamp = new Date().toISOString().split("T")[0];
    downloadAsFile(
      blob as unknown as string,
      `chimera-export-${timestamp}.zip`,
      "application/zip"
    );
  } catch (error) {
    console.error("Error creating ZIP:", error);
    throw new Error("Failed to create ZIP export");
  }
}

/**
 * Export options for UI
 */
export interface ExportOption {
  id: string;
  label: string;
  description: string;
  icon?: string;
}

export const EXPORT_OPTIONS: ExportOption[] = [
  {
    id: "single",
    label: "Single File",
    description: "Download as a single code file",
  },
  {
    id: "zip",
    label: "ZIP Package",
    description: "Download both teams in a ZIP",
  },
  {
    id: "clipboard",
    label: "Copy to Clipboard",
    description: "Copy code to clipboard",
  },
];
